### ISSUE TITLE
Path finding

### ISSUE THREAD

**Issue by supertassu** [UrsaOK/RogueLikeCreeperium#1]
Path  finding virhe!

**Comment by creeperium** [comment]
Hoidetaan

**Comment by supertassu** [comment]
Suljen issueen koska tämä hoidetaan.

**Comment by supertassu** [comment]
Avattu koska tämän hoidossa voi mennä jonkun aikaa.

**Comment by creeperium** [comment]
Suljen issuen koska path finding toimii taas.

**Comment by supertassu** [comment]
Kiitos. Issue on lukittu kommenteilta :)
